using FluentAssertions;
using HelpCenter.Application.Exceptions;
using HelpCenter.Application.Features.Requests.Commands.CloseRequest;
using HelpCenter.Application.Features.Requests.Commands.CreateRequest;
using HelpCenter.Application.Features.Requests.Commands.SendMessage;
using HelpCenter.Application.Features.Requests.Queries.GetAdminMessages;
using HelpCenter.Application.Features.Requests.Queries.GetAdminRequestById;
using HelpCenter.Application.Features.Requests.Queries.GetCustomerMessages;
using HelpCenter.Application.Features.Requests.Queries.GetCustomerRequestById;
using HelpCenter.Application.Interfaces;
using HelpCenter.Application.Tests.Common;
using HelpCenter.Domain.Entities;
using HelpCenter.Domain.Enums;
using HelpCenter.Persistence.Context.Seed.SampleData;
using MediatR;
using Microsoft.Extensions.Logging.Abstractions;
using NSubstitute;
using System.Linq;
using Xunit;

namespace HelpCenter.Application.Tests.Authorization;

public class CustomerIsolationAndSecurityTests : HandlerTestBase
{
    private readonly IFileService _fileService = Substitute.For<IFileService>();
    private readonly IRequestHubService _hubService = Substitute.For<IRequestHubService>();
    private readonly IPublisher _publisher = Substitute.For<IPublisher>();

    private readonly Guid _request1PublicId;
    private readonly Guid _request2PublicId;
    private readonly Guid _request3PublicId;

    public CustomerIsolationAndSecurityTests()
    {
        Db.Database.EnsureCreated();

        // SampleData is no longer embedded via HasData/migrations (see SampleDataSeeder) —
        // to keep it out of production, it is added through a runtime seed-runner that only runs
        // in Development/Staging. Tests should use the same runtime path; there is no environment
        // check here, and tests are treated as equivalent to Development.
        SampleDataSeeder.SeedAsync(Db).GetAwaiter().GetResult();

        // PublicId is generated by a ValueGenerator during SaveChangesAsync, so it is not known
        // at compile time on the C# side — we read the real value from the database
        // after seeding.
        _request1PublicId = Db.CustomerRequests.Single(x => x.Id == 1).PublicId;
        _request2PublicId = Db.CustomerRequests.Single(x => x.Id == 2).PublicId;
        _request3PublicId = Db.CustomerRequests.Single(x => x.Id == 3).PublicId;
    }

    [Fact]
    public async Task Customer_cannot_access_another_customers_ticket_details()
    {
        // Ahmet (Customer 1 / Acme) tries to access Request 2 (Mehmet / Beta)
        var handler = new GetCustomerRequestByIdQueryHandler(Uow, Mapper, NullLogger<GetCustomerRequestByIdQueryHandler>.Instance);
        var query = new GetCustomerRequestByIdQuery
        {
            CustomerId = 1, // Ahmet (Acme)
            PublicId = _request2PublicId // Request 2 belongs to Customer 3 (Beta)
        };

        Func<Task> act = async () => await handler.Handle(query, CancellationToken.None);

        await act.Should().ThrowAsync<RequestNotBelongToCustomerException>();
    }

    [Fact]
    public async Task Customer_cannot_fetch_another_customers_ticket_messages()
    {
        // Ahmet (Customer 1 / Acme) tries to read messages for Request 2 (Mehmet / Beta)
        var handler = new GetCustomerMessagesQueryHandler(Uow);
        var query = new GetCustomerMessagesQuery
        {
            CustomerId = 1, // Ahmet (Acme)
            RequestPublicId = _request2PublicId // Request 2 belongs to Customer 3 (Beta)
        };

        Func<Task> act = async () => await handler.Handle(query, CancellationToken.None);

        await act.Should().ThrowAsync<RequestNotBelongToCustomerException>();
    }

    [Fact]
    public async Task Customer_cannot_send_message_to_another_customers_ticket()
    {
        // Ahmet (Customer 1 / Acme) tries to inject a message into Request 2 (Mehmet / Beta)
        var handler = new SendMessageCommandHandler(
            Uow, _fileService, _hubService,
            NullLogger<SendMessageCommandHandler>.Instance);

        var command = new SendMessageCommand
        {
            CustomerId = 1, // Ahmet (Acme)
            RequestPublicId = _request2PublicId, // Request 2 belongs to Customer 3 (Beta)
            MessageText = "Hacking into Beta's conversation"
        };

        Func<Task> act = async () => await handler.Handle(command, CancellationToken.None);

        await act.Should().ThrowAsync<RequestNotBelongToCustomerException>();
    }

    [Fact]
    public async Task Customer_cannot_close_another_customers_ticket()
    {
        // Ahmet (Customer 1 / Acme) tries to close Request 2 (Mehmet / Beta)
        var handler = new CloseRequestCommandHandler(Uow);
        var command = new CloseRequestCommand
        {
            CustomerId = 1, // Ahmet (Acme)
            PublicId = _request2PublicId // Request 2 belongs to Customer 3 (Beta)
        };

        Func<Task> act = async () => await handler.Handle(command, CancellationToken.None);

        await act.Should().ThrowAsync<RequestNotBelongToCustomerException>();
    }

    [Fact]
    public async Task Internal_notes_are_strictly_hidden_from_customer_messages_endpoint()
    {
        // Ahmet (Customer 1 / Acme) reads messages for his own Request 1
        var handler = new GetCustomerMessagesQueryHandler(Uow);
        var query = new GetCustomerMessagesQuery
        {
            CustomerId = 1,
            RequestPublicId = _request1PublicId
        };

        var messages = await handler.Handle(query, CancellationToken.None);

        messages.Should().NotBeEmpty();
        // Should contain public customer message & public agent reply
        messages.Should().Contain(m => m.MessageText.Contains("Fatura keserken 500 hatası alıyoruz"));
        messages.Should().Contain(m => m.MessageText.Contains("teknik uzmanımıza yönlendirdim"));

        // Must NEVER contain the internal note
        messages.Should().NotContain(m => m.Type == MessageType.InternalNote);
        messages.Should().NotContain(m => m.MessageText.Contains("[İÇ NOT]"));
    }

    [Fact]
    public async Task Internal_notes_are_visible_to_internal_staff_in_admin_messages_endpoint()
    {
        // Staff reads messages for Request 1
        var userContext = Substitute.For<IUserContext>();
        userContext.UserId.Returns(1);
        var handler = new GetAdminMessagesQueryHandler(Uow, userContext);
        var query = new GetAdminMessagesQuery
        {
            RequestPublicId = _request1PublicId,
            PageSize = 20
        };

        var response = await handler.Handle(query, CancellationToken.None);

        response.Messages.Should().NotBeEmpty();
        response.Messages.Should().Contain(m => m.Type == MessageType.InternalNote);
        response.Messages.Should().Contain(m => m.MessageText.Contains("[İÇ NOT]"));
    }

    [Fact]
    public async Task Assigned_staff_cannot_read_another_tickets_detail_or_messages()
    {
        var assignedRequest = Db.CustomerRequests.First(x => x.AssignedUserId != null || x.CurrentExpertId != null);
        var outsiderContext = Substitute.For<IUserContext>();
        outsiderContext.UserId.Returns(Db.Users.Max(x => x.Id) + 1);

        var detailHandler = new GetAdminRequestByIdQueryHandler(Uow, Mapper, outsiderContext);
        var detail = () => detailHandler.Handle(
            new GetAdminRequestByIdQuery(assignedRequest.PublicId, OnlyAssignedToCurrentUser: true),
            CancellationToken.None);

        var messagesHandler = new GetAdminMessagesQueryHandler(Uow, outsiderContext);
        var messages = () => messagesHandler.Handle(new GetAdminMessagesQuery
        {
            RequestPublicId = assignedRequest.PublicId,
            OnlyAssignedToCurrentUser = true
        }, CancellationToken.None);

        await detail.Should().ThrowAsync<RequestNotFoundException>();
        await messages.Should().ThrowAsync<RequestNotFoundException>();
    }

    [Fact]
    public async Task Customer_cannot_send_message_to_a_completed_closed_ticket()
    {
        // Ayse (Customer 2 / Acme) tries to post a message to Request 3 (Completed / Closed)
        var handler = new SendMessageCommandHandler(
            Uow, _fileService, _hubService,
            NullLogger<SendMessageCommandHandler>.Instance);

        var command = new SendMessageCommand
        {
            CustomerId = 2, // Ayse
            RequestPublicId = _request3PublicId, // Request 3 is Completed
            MessageText = "Can you reopen this ticket?"
        };

        Func<Task> act = async () => await handler.Handle(command, CancellationToken.None);

        await act.Should().ThrowAsync<RequestCompletedException>();
    }

    [Fact]
    public async Task Customer_cannot_create_request_for_unlicensed_module()
    {
        // Ahmet (Acme / Company 1 has Module 1 and 2, but NOT Module 4 - API)
        var createRules = new CreateRequestRules(Uow);
        var handler = new CreateRequestCommandHandler(
            Uow, createRules, _fileService, _publisher,
            NullLogger<CreateRequestCommandHandler>.Instance);

        var command = new CreateRequestCommand
        {
            CustomerId = 1, // Ahmet (Acme)
            ModuleId = 4, // Module 4 (API) is licensed to Beta, not Acme
            Title = "Need API Access",
            MessageText = "Please give us API tokens",
            Priority = RequestPriority.Medium
        };

        Func<Task> act = async () => await handler.Handle(command, CancellationToken.None);

        await act.Should().ThrowAsync<ModuleNotAllowedForCompanyException>();
    }
}
